"""The V5 flake generator and `vendomat sync` (GEN-005 to GEN-008, GEN-015 to GEN-022)."""

from __future__ import annotations

import os
import stat
from pathlib import Path

import pytest
from nixfixture import CANDIDATE_REGISTRY, candidate_flake, without_digest
from typer.testing import CliRunner

from vendomat.cli import app
from vendomat.generate import GenerateError, render, sync_flake
from vendomat.registry import parse_registry

runner = CliRunner()
VERSION = "9.9.9"
OUTPUTS = "inputs: { }\n"


@pytest.fixture
def project(tmp_path: Path) -> Path:
    (tmp_path / "vendomat.toml").write_text(CANDIDATE_REGISTRY)
    (tmp_path / "flake-outputs.nix").write_text(OUTPUTS)
    return tmp_path


def test_render_matches_the_candidate_that_passed_on_nix():
    registry = parse_registry(CANDIDATE_REGISTRY)
    expected = candidate_flake(version=VERSION, digest=registry.digest)
    assert render(registry, VERSION) == expected


def test_header_names_tool_version_and_digest_on_the_first_two_lines():
    registry = parse_registry(CANDIDATE_REGISTRY)
    first, second = render(registry, VERSION).splitlines()[:2]
    assert first == "# GENERATED by vendomat 9.9.9. Do not edit."
    assert second == f"# registry-digest: {registry.digest}"


def test_one_input_per_registry_entry_and_no_implicit_input():
    text = render(parse_registry(CANDIDATE_REGISTRY), VERSION)
    declared = {line.split(".")[0].strip() for line in text.splitlines() if ".url = " in line}
    assert declared == {"data", "mod-pkg", "nixpkgs", "plain"}
    assert "devenv" not in declared


def test_generated_flake_has_no_shell_and_no_module_scan():
    text = render(parse_registry(CANDIDATE_REGISTRY), VERSION)
    body = text.split("{", 1)[1]
    for banned in ("devShells", "mkShell", "filterAttrs", "devenvModules", "nixosModules", "homeManagerModules"):
        assert banned not in body
    assert "outputs = inputs: import ./flake-outputs.nix inputs;" in body


def test_follows_edges_are_emitted_only_for_declared_children():
    registry = parse_registry(
        '[inputs]\na = { url = "path:./a" }\nb = { url = "path:./b" }\n[passthrough]\nnixpkgs = { url = "x:np" }\n'
        '[follows]\na = ["nixpkgs"]\n'
    )
    text = render(registry, VERSION)
    assert 'a.inputs.nixpkgs.follows = "nixpkgs";' in text
    assert text.count(".follows") == 1


def test_names_that_nix_cannot_write_bare_are_quoted():
    registry = parse_registry(
        '[inputs]\n3d-lib = { url = "path:./a" }\nrec = { url = "path:./b" }\nplain = { url = "path:./c" }\n'
    )
    text = render(registry, VERSION)
    assert '"3d-lib".url = "path:./a";' in text
    assert '"rec".url = "path:./b";' in text
    assert "    plain.url" in text


def test_ref_and_rev_reach_the_generated_url():
    registry = parse_registry('[inputs]\na = { url = "git+https://h/a", ref = "refs/tags/v1.0.0" }\n')
    assert 'a.url = "git+https://h/a?ref=refs/tags/v1.0.0";' in render(registry, VERSION)


FORGE_REGISTRY = """
[forge]
url = "git://server/"

[inputs]
lib-a = { ref = "refs/tags/v1.0.0" }
loci-nvim = { repo = "loci.nvim", ref = "refs/tags/v1.2.0", keep = true }
telescope = { url = "github:upstream/telescope.nvim", ref = "refs/tags/v0.1.8", flake = false, mirror = true }

[passthrough]
nixpkgs = { url = "github:cachix/devenv-nixpkgs/rolling", backup = "https://backup.example/nixpkgs" }
"""


def test_forge_entries_resolve_to_the_collection_with_the_tag_in_the_url():
    text = render(parse_registry(FORGE_REGISTRY), VERSION)
    assert 'lib-a.url = "git://server/lib-a?ref=refs/tags/v1.0.0";' in text
    assert 'loci-nvim.url = "git://server/loci.nvim?ref=refs/tags/v1.2.0";' in text
    assert 'telescope.url = "github:upstream/telescope.nvim?ref=refs/tags/v0.1.8";' in text
    assert "telescope.flake = false;" in text


def test_collection_flags_and_backup_never_reach_the_generated_flake():
    plain = FORGE_REGISTRY.replace(", keep = true", "").replace(", mirror = true", "")
    plain = plain.replace(', backup = "https://backup.example/nixpkgs"', "")
    flagged, bare = parse_registry(FORGE_REGISTRY), parse_registry(plain)
    assert flagged.digest == bare.digest
    assert render(flagged, VERSION) == render(bare, VERSION)
    assert "backup.example" not in render(flagged, VERSION)


def test_sync_twice_gives_identical_bytes_and_does_not_rewrite(project: Path):
    first = sync_flake(project, VERSION)
    assert first.changed
    flake = project / "flake.nix"
    before, mtime = flake.read_bytes(), flake.stat().st_mtime_ns
    second = sync_flake(project, VERSION)
    assert not second.changed
    assert flake.read_bytes() == before
    assert flake.stat().st_mtime_ns == mtime
    assert not list(project.glob(".flake.nix*"))


def test_sync_ignores_registry_comments_and_follows_registry_content(project: Path):
    sync_flake(project, VERSION)
    first = (project / "flake.nix").read_text()
    (project / "vendomat.toml").write_text(CANDIDATE_REGISTRY + "\n# a comment\n")
    sync_flake(project, VERSION)
    assert (project / "flake.nix").read_text() == first
    (project / "vendomat.toml").write_text(CANDIDATE_REGISTRY.replace("plain", "other"))
    sync_flake(project, VERSION)
    assert without_digest((project / "flake.nix").read_text()) != without_digest(first)


def test_sync_leaves_registry_lock_and_outputs_untouched_and_unread(project: Path):
    lock = project / "flake.lock"
    lock.write_text('{"sentinel": true}\n')
    registry_before = (project / "vendomat.toml").read_bytes()
    outputs_before = (project / "flake-outputs.nix").read_bytes()
    lock_before = lock.read_bytes()
    stamps = {p: p.stat().st_mtime_ns for p in (lock, project / "flake-outputs.nix", project / "vendomat.toml")}
    # No read and no write permission: any open() of these files would fail the call.
    os.chmod(lock, 0)
    os.chmod(project / "flake-outputs.nix", 0)
    try:
        sync_flake(project, VERSION)
    finally:
        os.chmod(lock, stat.S_IRUSR | stat.S_IWUSR)
        os.chmod(project / "flake-outputs.nix", stat.S_IRUSR | stat.S_IWUSR)
    assert lock.read_bytes() == lock_before
    assert (project / "flake-outputs.nix").read_bytes() == outputs_before
    assert (project / "vendomat.toml").read_bytes() == registry_before
    assert {p: p.stat().st_mtime_ns for p in stamps} == stamps


def test_sync_refuses_a_hand_authored_flake_and_names_it(project: Path):
    flake = project / "flake.nix"
    flake.write_text("{ outputs = _: { }; }\n")
    with pytest.raises(GenerateError, match="flake.nix: this flake.nix has no generated header") as caught:
        sync_flake(project, VERSION)
    assert caught.value.code == 1
    assert flake.read_text() == "{ outputs = _: { }; }\n"


def test_sync_without_the_project_outputs_file_fails_before_any_write(project: Path):
    (project / "flake-outputs.nix").unlink()
    with pytest.raises(GenerateError, match="flake-outputs.nix: the project-owned outputs file is missing"):
        sync_flake(project, VERSION)
    assert not (project / "flake.nix").exists()


def test_sync_without_a_registry_names_the_file(tmp_path: Path):
    with pytest.raises(GenerateError, match="vendomat.toml: no registry here"):
        sync_flake(tmp_path, VERSION)


def test_sync_with_an_invalid_registry_writes_nothing(project: Path):
    (project / "vendomat.toml").write_text('[inputs]\nNvim_Review = { url = "x:y" }\n')
    with pytest.raises(GenerateError, match="Nvim_Review"):
        sync_flake(project, VERSION)
    assert not (project / "flake.nix").exists()


def test_cli_sync_writes_then_reports_unchanged(project: Path):
    first = runner.invoke(app, ["sync", "--root", str(project)])
    assert first.exit_code == 0, first.output
    assert "wrote flake.nix (4 direct input(s))" in first.output
    second = runner.invoke(app, ["sync", "--root", str(project)])
    assert second.exit_code == 0
    assert "unchanged flake.nix" in second.output


def test_cli_sync_exit_codes_and_causes(project: Path):
    (project / "flake.nix").write_text("{ }\n")
    refused = runner.invoke(app, ["sync", "--root", str(project)])
    assert refused.exit_code == 1
    assert "flake.nix" in refused.output
    (project / "flake.nix").unlink()
    (project / "flake-outputs.nix").unlink()
    missing = runner.invoke(app, ["sync", "--root", str(project)])
    assert missing.exit_code == 2
    assert "flake-outputs.nix" in missing.output


def test_cli_sync_without_a_registry_names_the_missing_file(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 2
    assert "vendomat.toml: no registry here" in result.output
