"""The pre-resolver writes the `.vendomat/` fragment (`PRE-001` to `PRE-011`).

A fake resolver answers every question about sources, so these checks need no network and no Nix.
"""

from __future__ import annotations

import json
import os
import stat
import textwrap
from pathlib import Path
from typing import Any

import pytest

from vendomat.defaults import DEFAULT_NIXPKGS_URL
from vendomat.devenvgen import (
    DevenvSyncError,
    ensure_lock,
    read_digest,
    render_yaml,
    sync_devenv,
)
from vendomat.nixio import Fetched, NixError, lock_problems, same_source
from vendomat.registry import parse_registry

TOOL = "0.7.0"


class FakeResolver:
    """Sources are directories under ``tmp_path``; flake children come from a table."""

    def __init__(self, sources: dict[str, Path], children: dict[str, dict[str, dict[str, Any]]] | None = None):
        self.sources = sources
        self.children = children or {}
        self.prefetched: list[str] = []
        self.listed: list[str] = []

    def prefetch(self, url: str) -> Fetched:
        self.prefetched.append(url)
        if url not in self.sources:
            raise NixError(f"fetch {url}: unreachable")
        return Fetched(str(self.sources[url]), "sha256-" + url.replace("/", "_"), None)

    def direct_inputs(self, url: str) -> dict[str, dict[str, Any]]:
        self.listed.append(url)
        return self.children.get(url, {})


def project(tmp_path: Path, toml: str) -> Path:
    root = tmp_path / "ws"
    root.mkdir()
    (root / "vendomat.toml").write_text(textwrap.dedent(toml))
    return root


def source(tmp_path: Path, name: str, yaml: str | None) -> Path:
    path = tmp_path / "src" / name
    path.mkdir(parents=True)
    if yaml is not None:
        (path / "devenv.yaml").write_text(textwrap.dedent(yaml))
    return path


NIXPKGS = "github:NixOS/nixpkgs/e7439b6b14ad3cc35d05608ebca9bce01a25f5f8"


def run(root: Path, resolver: FakeResolver, **kw: Any):
    registry = parse_registry((root / "vendomat.toml").read_text())
    kw.setdefault("update_lock", False)
    return sync_devenv(root, registry, TOOL, resolver, **kw)


def test_the_fragment_has_three_files_and_every_input(tmp_path):
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        data = { url = "path:/x/data", flake = false }
        """,
    )
    result = run(root, FakeResolver({}))
    assert result.changed and not result.skipped
    names = sorted(p.name for p in (root / ".vendomat").iterdir())
    assert names == ["devenv.nix", "devenv.yaml", "digest"]
    text = (root / ".vendomat" / "devenv.yaml").read_text()
    assert "# GENERATED by vendomat 0.7.0" in text
    assert f'url: "{DEFAULT_NIXPKGS_URL}"' in text
    assert "flake: false" in text
    assert any("release default" in n for n in result.notes)


def test_a_registry_nixpkgs_overrides_the_default_and_is_reported(tmp_path):
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        [passthrough]
        nixpkgs = { url = "github:NixOS/nixpkgs/nixos-unstable" }
        """,
    )
    result = run(root, FakeResolver({}))
    assert any("overrides the release default" in n for n in result.notes)
    assert "nixos-unstable" in (root / ".vendomat" / "devenv.yaml").read_text()


def test_three_level_imports_lift_each_input_once(tmp_path):
    a = source(
        tmp_path, "a", "inputs:\n  lib-b:\n    url: git://s/lib-b?ref=refs/tags/v1\nimports:\n  - lib-b/devenv\n"
    )
    b = source(tmp_path, "b", "inputs:\n  lib-c:\n    url: git://s/lib-c?ref=refs/tags/v1\nimports:\n  - lib-c\n")
    c = source(tmp_path, "c", "inputs:\n  leaf:\n    url: git://s/leaf?ref=refs/tags/v1\n    flake: false\n")
    (b / "devenv").mkdir()
    (b / "devenv" / "devenv.yaml").write_text(
        "inputs:\n  lib-c:\n    url: git://s/lib-c?ref=refs/tags/v1\nimports:\n  - lib-c\n"
    )
    (a / "devenv").mkdir()
    (a / "devenv" / "devenv.yaml").write_text((a / "devenv.yaml").read_text())
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        lib-a = { url = "git://s/lib-a", ref = "refs/tags/v1" }
        [imports]
        lib-a = "devenv"
        """,
    )
    resolver = FakeResolver(
        {
            "git://s/lib-a?ref=refs/tags/v1": a,
            "git://s/lib-b?ref=refs/tags/v1": b,
            "git://s/lib-c?ref=refs/tags/v1": c,
        }
    )
    result = run(root, resolver)
    text = (root / ".vendomat" / "devenv.yaml").read_text()
    for name in ("lib-a", "lib-b", "lib-c", "leaf"):
        assert text.count(f"\n  {name}:\n") == 1
    assert result.imports == 3
    digest = read_digest(root / ".vendomat" / "digest")
    assert {k for k in digest if k.startswith("import")} == {"import"} or "import" in digest


def test_import_reads_yaml_below_flake_dir(tmp_path):
    checkout = tmp_path / "checkout"
    module = checkout / "sources" / "greeting" / "devenv"
    module.mkdir(parents=True)
    (module / "devenv.yaml").write_text("inputs:\n  greeting-defaults:\n    url: git://s/defaults?ref=refs/tags/v1\n")
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        greeting = { url = "git://s/demo", ref = "refs/tags/v1", dir = "sources/greeting" }
        [imports]
        greeting = "devenv"
        """,
    )
    resolver = FakeResolver({"git://s/demo?ref=refs/tags/v1&dir=sources/greeting": checkout})
    result = run(root, resolver)
    assert result.inputs == 3
    assert "greeting-defaults:" in (root / ".vendomat" / "devenv.yaml").read_text()


def test_two_imports_that_disagree_on_a_url_are_an_error_naming_both(tmp_path):
    a = source(tmp_path, "a", "inputs:\n  shared:\n    url: git://s/shared?ref=refs/tags/v1\n")
    b = source(tmp_path, "b", "inputs:\n  shared:\n    url: git://s/shared?ref=refs/tags/v2\n")
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        lib-a = { url = "git://s/lib-a", ref = "refs/tags/v1" }
        lib-b = { url = "git://s/lib-b", ref = "refs/tags/v1" }
        [imports]
        lib-a = "."
        lib-b = "."
        """,
    )
    resolver = FakeResolver({"git://s/lib-a?ref=refs/tags/v1": a, "git://s/lib-b?ref=refs/tags/v1": b})
    with pytest.raises(DevenvSyncError) as info:
        run(root, resolver)
    message = str(info.value)
    assert "shared" in message and "lib-a" in message and "lib-b" in message and "v1" in message and "v2" in message
    assert info.value.code == 1
    assert not (root / ".vendomat").exists()


def test_a_registry_entry_wins_over_an_imported_url_and_is_reported(tmp_path):
    a = source(tmp_path, "a", "inputs:\n  shared:\n    url: git://s/shared?ref=refs/tags/v1\n")
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        lib-a = { url = "git://s/lib-a", ref = "refs/tags/v1" }
        shared = { url = "git://s/shared", ref = "refs/tags/v9" }
        [imports]
        lib-a = "."
        """,
    )
    result = run(root, FakeResolver({"git://s/lib-a?ref=refs/tags/v1": a}, {"git://s/shared?ref=refs/tags/v9": {}}))
    assert any("registry wins" in n and "shared" in n for n in result.notes)
    assert "refs/tags/v9" in (root / ".vendomat" / "devenv.yaml").read_text()


def test_an_import_cycle_is_an_error(tmp_path):
    a = source(tmp_path, "a", "imports:\n  - lib-b\n")
    b = source(tmp_path, "b", "imports:\n  - lib-a\n")
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        lib-a = { url = "git://s/lib-a", ref = "refs/tags/v1" }
        lib-b = { url = "git://s/lib-b", ref = "refs/tags/v1" }
        [imports]
        lib-a = "."
        """,
    )
    resolver = FakeResolver({"git://s/lib-a?ref=refs/tags/v1": a, "git://s/lib-b?ref=refs/tags/v1": b})
    with pytest.raises(DevenvSyncError, match="import cycle: lib-a -> lib-b -> lib-a"):
        run(root, resolver)


def test_follows_are_one_level_and_only_for_a_shared_source(tmp_path):
    root = project(
        tmp_path,
        f"""
        [targets]
        devenv = true
        [inputs]
        lib-a = {{ url = "git://s/lib-a", ref = "refs/tags/v1" }}
        [passthrough]
        nixpkgs = {{ url = "{NIXPKGS}" }}
        """,
    )
    children = {
        "git://s/lib-a?ref=refs/tags/v1": {
            "nixpkgs": {
                "type": "github",
                "owner": "NixOS",
                "repo": "nixpkgs",
                "rev": "e7439b6b14ad3cc35d05608ebca9bce01a25f5f8",
            },
            "other": {"type": "github", "owner": "o", "repo": "x"},
        }
    }
    result = run(root, FakeResolver({}, children))
    text = (root / ".vendomat" / "devenv.yaml").read_text()
    assert 'follows: "nixpkgs"' in text
    assert text.count("follows:") == 1
    assert not any("other" in n for n in result.notes)  # `other` is no top-level input: silent


def test_a_child_with_a_different_source_is_reported_not_followed(tmp_path):
    root = project(
        tmp_path,
        f"""
        [targets]
        devenv = true
        [inputs]
        lib-a = {{ url = "git://s/lib-a", ref = "refs/tags/v1" }}
        [passthrough]
        nixpkgs = {{ url = "{NIXPKGS}" }}
        """,
    )
    children = {
        "git://s/lib-a?ref=refs/tags/v1": {
            "nixpkgs": {"type": "github", "owner": "NixOS", "repo": "nixpkgs", "ref": "nixos-24.05"}
        }
    }
    result = run(root, FakeResolver({}, children))
    assert "follows:" not in (root / ".vendomat" / "devenv.yaml").read_text()
    assert any("differs from top-level 'nixpkgs'" in n for n in result.notes)


def test_a_registry_follows_entry_is_written_without_asking_nix(tmp_path):
    root = project(
        tmp_path,
        f"""
        [targets]
        devenv = true
        [inputs]
        lib-a = {{ url = "git://s/lib-a", ref = "refs/tags/v1" }}
        [passthrough]
        nixpkgs = {{ url = "{NIXPKGS}" }}
        [follows]
        lib-a = ["nixpkgs"]
        """,
    )
    run(root, FakeResolver({}))
    assert 'follows: "nixpkgs"' in (root / ".vendomat" / "devenv.yaml").read_text()


def test_an_unchanged_workspace_makes_no_resolver_call_and_writes_nothing(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    run(root, FakeResolver({}))
    before = {p.name: p.stat().st_mtime_ns for p in (root / ".vendomat").iterdir()}
    resolver = FakeResolver({})
    result = run(root, resolver)
    assert result.skipped and not result.changed
    assert resolver.prefetched == [] and resolver.listed == []
    assert before == {p.name: p.stat().st_mtime_ns for p in (root / ".vendomat").iterdir()}


def test_a_changed_registry_rewrites_and_the_digest_follows(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    run(root, FakeResolver({}))
    first = read_digest(root / ".vendomat" / "digest")
    (root / "vendomat.toml").write_text('[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/y", flake = false }\n')
    result = run(root, FakeResolver({}))
    second = read_digest(root / ".vendomat" / "digest")
    assert result.changed and first["registry"] != second["registry"] and first["fragment"] != second["fragment"]
    assert 'url: "path:/y"' in (root / ".vendomat" / "devenv.yaml").read_text()


def test_an_edited_fragment_is_regenerated(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    run(root, FakeResolver({}))
    fragment = root / ".vendomat" / "devenv.yaml"
    fragment.write_text(fragment.read_text() + "# hand edit\n")
    result = run(root, FakeResolver({}))
    assert result.changed
    assert "hand edit" not in fragment.read_text()


def test_replacement_gives_each_file_a_later_modification_time(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    run(root, FakeResolver({}))
    fragment = root / ".vendomat" / "devenv.yaml"
    old = fragment.stat().st_mtime_ns
    os.utime(fragment, ns=(old, old))
    (root / "vendomat.toml").write_text('[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/z", flake = false }\n')
    run(root, FakeResolver({}))
    assert fragment.stat().st_mtime_ns > old


def test_the_eval_cache_is_cleared_when_the_inputs_change(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    run(root, FakeResolver({}))
    state = root / ".devenv"
    state.mkdir()
    (state / "nix-eval-cache.db").write_text("stale")
    (state / "keep").write_text("keep")
    (root / "vendomat.toml").write_text('[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/q", flake = false }\n')
    run(root, FakeResolver({}))
    assert not (state / "nix-eval-cache.db").exists()
    assert (state / "keep").exists()


def test_a_dry_run_writes_nothing(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    result = run(root, FakeResolver({}), dry_run=True)
    assert result.changed
    assert not (root / ".vendomat").exists()


def test_a_workspace_that_redeclares_a_generated_input_gets_a_warning(tmp_path):
    root = project(tmp_path, '[targets]\ndevenv = true\n[inputs]\nd = { url = "path:/x", flake = false }\n')
    (root / "devenv.yaml").write_text("imports:\n  - ./.vendomat\ninputs:\n  d:\n    url: path:/other\n")
    result = run(root, FakeResolver({}))
    assert any("devenv.yaml declares input 'd'" in w for w in result.warnings)


def test_the_unreachable_import_source_is_an_error_naming_the_import(tmp_path):
    root = project(
        tmp_path,
        """
        [targets]
        devenv = true
        [inputs]
        lib-a = { url = "git://s/lib-a", ref = "refs/tags/v1" }
        [imports]
        lib-a = "devenv"
        """,
    )
    with pytest.raises(DevenvSyncError, match=r"import 'lib-a/devenv': fetch .* unreachable"):
        run(root, FakeResolver({}))
    assert not (root / ".vendomat").exists()


def test_rendering_is_deterministic():
    from vendomat.devenvgen import InputSpec

    inputs = {"b": InputSpec("b", "u2"), "a": InputSpec("a", "u1", flake=False)}
    assert render_yaml(inputs, ["z", "y"], TOOL) == render_yaml(dict(reversed(inputs.items())), ["y", "z"], TOOL)


# --- the lock --------------------------------------------------------------------------------


def lock_with(**nodes: dict[str, Any]) -> dict[str, Any]:
    return {
        "nodes": {
            "root": {"inputs": {name: name for name in nodes}},
            **nodes,
        },
        "root": "root",
        "version": 7,
    }


def test_lock_problems_names_missing_and_moved_inputs():
    lock = lock_with(
        a={"locked": {"rev": "1" * 40}, "original": {"type": "git", "url": "git://s/a", "ref": "refs/tags/v1"}},
    )
    assert lock_problems(lock, {"a": "git://s/a?ref=refs/tags/v1"}) == []
    moved = lock_problems(lock, {"a": "git://s/a?ref=refs/tags/v2"})
    assert moved and moved[0][0] == "a"
    missing = lock_problems(lock, {"b": "git://s/b?ref=refs/tags/v1"})
    assert missing == [("b", "not in the lock")]
    assert lock_problems(None, {"x": "u"}) == [("x", "no devenv.lock")]


def test_same_source_is_unknown_for_a_form_it_does_not_read():
    assert same_source("flake:foo", {"type": "indirect", "id": "foo"}) is None


def stub_devenv(tmp_path: Path, body: str) -> str:
    script = tmp_path / "devenv-stub"
    script.write_text("#!/bin/sh\n" + textwrap.dedent(body))
    script.chmod(script.stat().st_mode | stat.S_IEXEC)
    return str(script)


GOOD_LOCK = json.dumps(
    lock_with(a={"locked": {"rev": "1" * 40}, "original": {"type": "git", "url": "git://s/a", "ref": "refs/tags/v1"}})
)


def test_ensure_lock_runs_update_when_the_lock_is_missing(tmp_path):
    root = tmp_path / "ws"
    root.mkdir()
    cmd = stub_devenv(tmp_path, f"cat > devenv.lock <<'EOF'\n{GOOD_LOCK}\nEOF\n")
    assert ensure_lock(root, {"a": "git://s/a?ref=refs/tags/v1"}, cmd) is True
    assert ensure_lock(root, {"a": "git://s/a?ref=refs/tags/v1"}, "/no/such/command") is False


def test_ensure_lock_updates_all_when_two_inputs_are_missing(tmp_path):
    root = tmp_path / "ws"
    root.mkdir()
    (root / "devenv.lock").write_text(json.dumps(lock_with()))
    complete = json.dumps(
        lock_with(
            a={"locked": {"rev": "1" * 40}, "original": {"type": "git", "url": "git://s/a", "ref": "refs/tags/v1"}},
            b={"locked": {"rev": "2" * 40}, "original": {"type": "git", "url": "git://s/b", "ref": "refs/tags/v1"}},
        )
    )
    cmd = stub_devenv(tmp_path, f"printf '%s\\n' \"$@\" > argv\ncat > devenv.lock <<'EOF'\n{complete}\nEOF\n")
    assert ensure_lock(root, {"a": "git://s/a?ref=refs/tags/v1", "b": "git://s/b?ref=refs/tags/v1"}, cmd)
    assert (root / "argv").read_text() == "update\n"


def test_a_failed_update_that_exits_zero_is_still_a_failure_and_keeps_the_prior_lock(tmp_path):
    root = tmp_path / "ws"
    root.mkdir()
    prior = json.dumps(lock_with(z={"locked": {"rev": "2" * 40}, "original": {"type": "git", "url": "git://s/z"}}))
    (root / "devenv.lock").write_text(prior)
    # Exit 0, print an error, write nothing: the stock behavior of `devenv update` (NAT-026).
    cmd = stub_devenv(tmp_path, "echo 'error: unable to download git://s/a' >&2\nexit 0\n")
    with pytest.raises(DevenvSyncError) as info:
        ensure_lock(root, {"a": "git://s/a?ref=refs/tags/v1", "z": "git://s/z"}, cmd)
    assert "a: not in the lock" in str(info.value)
    assert "prior devenv.lock is back in place" in str(info.value)
    assert "unable to download" in str(info.value)
    assert (root / "devenv.lock").read_text() == prior


def test_a_partial_lock_from_a_failed_update_is_rolled_back(tmp_path):
    root = tmp_path / "ws"
    root.mkdir()
    prior = json.dumps(lock_with(z={"locked": {"rev": "2" * 40}, "original": {"type": "git", "url": "git://s/z"}}))
    (root / "devenv.lock").write_text(prior)
    cmd = stub_devenv(tmp_path, 'echo \'{"nodes": {"root": {"inputs": {}}}, "root": "root"}\' > devenv.lock\nexit 1\n')
    with pytest.raises(DevenvSyncError):
        ensure_lock(root, {"a": "git://s/a?ref=refs/tags/v1"}, cmd)
    assert (root / "devenv.lock").read_text() == prior


def test_a_registry_nixpkgs_naming_the_default_revision_is_not_an_override(tmp_path):
    root = project(
        tmp_path,
        f"""
        [targets]
        devenv = true
        [inputs]
        [passthrough]
        nixpkgs = {{ url = "github:NixOS/nixpkgs", rev = "{DEFAULT_NIXPKGS_URL.rsplit("/", 1)[1]}" }}
        """,
    )
    result = run(root, FakeResolver({}))
    assert not any("overrides" in n for n in result.notes)
