"""Write the ``.vendomat/`` fragment of a devenv workspace (``PRE-001`` to ``PRE-011``).

``sync`` reads ``vendomat.toml`` and writes three files into ``.vendomat/``:

* ``devenv.yaml``: every input as a top-level input, each flake input with one-level ``follows``
  so a source has one lock node, and the imports the registry names.
* ``devenv.nix``: assertions that stop the shell when the registry or the fragment changed since
  the last sync.
* ``digest``: the hashes those assertions compare.

The workspace ``devenv.yaml`` holds only ``imports: [ ./.vendomat ]``. devenv writes
``devenv.lock``. This module never writes the lock itself (``NAT-026``): it asks ``devenv update``
to, and then compares the result with the requested inputs.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import yamlsubset
from .defaults import DEFAULT_NIXPKGS_URL
from .nixio import NixError, NixResolver, Resolver, canon_url, lock_problems, same_source
from .registry import Registry

FRAGMENT_DIR = ".vendomat"
YAML_FILE = "devenv.yaml"
NIX_FILE = "devenv.nix"
DIGEST_FILE = "digest"
REGISTRY_FILE = "vendomat.toml"
HEADER = "# GENERATED by vendomat {tool}. Do not edit."
#: Seconds. ``devenv update`` may fetch several inputs.
UPDATE_TIMEOUT = 1800


class DevenvSyncError(Exception):
    """A refusal or a fault. ``code`` is the CLI exit status: 1 needs a decision, 2 is a fault."""

    def __init__(self, message: str, code: int = 2) -> None:
        super().__init__(message)
        self.code = code


@dataclass
class InputSpec:
    """One top-level input of the fragment."""

    name: str
    url: str
    flake: bool = True
    follows: dict[str, str] = field(default_factory=dict)
    origin: str = "registry"


@dataclass(frozen=True)
class DevenvResult:
    """What ``sync_devenv`` did. ``changed`` says a file differs from the new text."""

    path: Path
    changed: bool
    inputs: int
    imports: int
    notes: tuple[str, ...] = ()
    warnings: tuple[str, ...] = ()
    lock_updated: bool = False
    skipped: bool = False


NIX_MODULE = r"""# GENERATED by vendomat {tool}. Do not edit.
# A failing task before enterShell does not stop `devenv shell`. An assertion does, so the freshness
# check is an assertion. devenv evaluates assertions for shell, test, and up (not for build or eval).
{{ lib, config, ... }}:
let
  root = config.devenv.root;
  digestPath = /. + "${{root}}/.vendomat/digest";
  registryPath = /. + "${{root}}/vendomat.toml";
  fragmentPath = /. + "${{root}}/.vendomat/devenv.yaml";
  recorded =
    key:
    let
      hits = lib.filter (l: lib.hasPrefix "${{key}} " l) (lib.splitString "\n" (builtins.readFile digestPath));
    in
    if hits == [ ] then "missing" else lib.removePrefix "${{key}} " (builtins.head hits);
  haveDigest = builtins.pathExists digestPath;
in
{{
  assertions = [
    {{
      assertion = haveDigest;
      message = "vendomat: .vendomat/digest is missing. Run: vendomat sync";
    }}
    {{
      assertion = !haveDigest || builtins.hashFile "sha256" registryPath == recorded "registry";
      message = "vendomat: STALE. vendomat.toml changed since the last sync. Run: vendomat sync";
    }}
    {{
      assertion = !haveDigest || builtins.hashFile "sha256" fragmentPath == recorded "fragment";
      message = "vendomat: STALE. .vendomat/devenv.yaml was edited by hand. Run: vendomat sync";
    }}
  ];
}}
"""


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_digest(path: Path) -> dict[str, str]:
    """Read ``.vendomat/digest`` into ``{key: value}``. A missing or unreadable file gives ``{}``."""

    try:
        text = path.read_text()
    except OSError:
        return {}
    out: dict[str, str] = {}
    for line in text.splitlines():
        key, _, value = line.partition(" ")
        if key and value:
            out[key] = value
    return out


# --- Discovery -------------------------------------------------------------------------------


class _Discovery:
    """Collect the top-level inputs: the registry, the default, and every imported ``devenv.yaml``."""

    def __init__(self, registry: Registry, resolver: Resolver) -> None:
        self.registry = registry
        self.resolver = resolver
        self.inputs: dict[str, InputSpec] = {}
        self.imports: list[str] = []
        self.resolved: dict[str, str] = {}
        self.notes: list[str] = []
        self._done: set[str] = set()
        self._declared_in: dict[str, str] = {}

    def run(self) -> None:
        for source in self.registry.sources:
            spec = InputSpec(name=source.name, url=source.url, flake=source.flake, origin="registry")
            spec.follows = {child: child for child in source.follows}
            self.inputs[source.name] = spec
        if "nixpkgs" not in self.inputs:
            self.inputs["nixpkgs"] = InputSpec("nixpkgs", DEFAULT_NIXPKGS_URL, origin="default")
            self.notes.append(f"nixpkgs: the registry names none; using the release default {DEFAULT_NIXPKGS_URL}")
        elif self.inputs["nixpkgs"].url != DEFAULT_NIXPKGS_URL and (
            canon_url(self.inputs["nixpkgs"].url) is None
            or canon_url(self.inputs["nixpkgs"].url) != canon_url(DEFAULT_NIXPKGS_URL)
        ):
            self.notes.append(f"nixpkgs: the registry overrides the release default with {self.inputs['nixpkgs'].url}")
        for imp in self.registry.imports:
            self._walk(imp, [])

    def _split(self, imp: str) -> tuple[str, str]:
        name, _, directory = imp.partition("/")
        return name, directory

    def _walk(self, imp: str, chain: list[str]) -> None:
        if imp in chain:
            raise DevenvSyncError("import cycle: " + " -> ".join([*chain, imp]), code=1)
        if imp in self._done:
            return
        name, directory = self._split(imp)
        if name not in self.inputs:
            via = f" (imported by {chain[-1]})" if chain else ""
            raise DevenvSyncError(f"import '{imp}'{via} names input '{name}', which no file declares", code=1)
        self.imports.append(imp)
        try:
            fetched = self.resolver.prefetch(self.inputs[name].url)
        except NixError as exc:
            raise DevenvSyncError(f"import '{imp}': {exc}") from exc
        self.resolved[imp] = fetched.nar_hash
        base = Path(fetched.store_path)
        self._read_yaml(imp, base, directory, chain)
        self._done.add(imp)

    def _read_yaml(self, imp: str, base: Path, directory: str, chain: list[str]) -> None:
        yaml_path = (base / directory / "devenv.yaml") if directory else (base / "devenv.yaml")
        if not yaml_path.is_file():
            return
        where = f"{imp}:devenv.yaml"
        try:
            doc = yamlsubset.parse(yaml_path.read_text(), where)
        except (OSError, yamlsubset.YamlError) as exc:
            raise DevenvSyncError(f"import '{imp}': cannot read its devenv.yaml: {exc}", code=1) from exc
        declared = doc.get("inputs") or {}
        if not isinstance(declared, dict):
            raise DevenvSyncError(f"import '{imp}': 'inputs' in its devenv.yaml must be a map", code=1)
        for name, raw in declared.items():
            self._add(name, raw, imp)
        for nested in doc.get("imports") or []:
            if not isinstance(nested, str):
                continue
            if nested.startswith("."):
                self._read_relative(imp, base, directory, nested, chain)
            else:
                self._walk(nested.rstrip("/"), [*chain, imp])

    def _read_relative(self, imp: str, base: Path, directory: str, rel: str, chain: list[str]) -> None:
        target = os.path.normpath(os.path.join(directory, rel))
        if target.startswith(".."):
            raise DevenvSyncError(f"import '{imp}': local import '{rel}' leaves the input source", code=1)
        self._read_yaml(imp, base, "" if target == "." else target, chain)

    def _add(self, name: str, raw: object, origin: str) -> None:
        body_in: dict[str, Any] = {}
        if isinstance(raw, str):
            body_in = {"url": raw}
        elif isinstance(raw, dict):
            body_in = {str(key): value for key, value in raw.items()}
        url_value = body_in.get("url")
        if not isinstance(url_value, str):
            raise DevenvSyncError(f"import '{origin}': input '{name}' has no 'url'", code=1)
        url: str = url_value
        existing = self.inputs.get(name)
        if existing is not None:
            if existing.url == url:
                return
            if existing.origin in ("registry", "default"):
                self.notes.append(
                    f"input '{name}': the registry wins; it ignores {url} from {origin}"
                    if existing.origin == "registry"
                    else f"input '{name}': the release default wins over {url} from {origin}"
                )
                return
            raise DevenvSyncError(
                f"input '{name}' has two sources: {existing.url} (from {existing.origin}) and {url} (from {origin}). "
                f"Name one in vendomat.toml [inputs] to choose",
                code=1,
            )
        spec = InputSpec(name=name, url=url, flake=body_in.get("flake") is not False, origin=origin)
        children = body_in.get("inputs") or {}
        if isinstance(children, dict):
            for child, body in children.items():
                follows = body.get("follows") if isinstance(body, dict) else None
                if isinstance(follows, str) and "/" not in follows:
                    spec.follows[str(child)] = follows
                elif follows is not None or (isinstance(body, dict) and "inputs" in body):
                    self.notes.append(
                        f"input '{name}' (from {origin}): ignored '{child}'; only one-level follows to a "
                        "top-level input are written (NAT-036)"
                    )
        self.inputs[name] = spec

    def follows(self) -> None:
        """Add ``follows`` for each child input that shares a top-level source (``PRE-005``)."""

        for spec in list(self.inputs.values()):
            if not spec.flake:
                continue
            try:
                children = self.resolver.direct_inputs(spec.url)
            except NixError as exc:
                raise DevenvSyncError(f"input '{spec.name}': {exc}") from exc
            for child, original in sorted(children.items()):
                if child == spec.name or child in spec.follows:
                    continue
                target = self.inputs.get(child)
                if target is None:
                    continue
                same = same_source(target.url, original)
                if same is True:
                    spec.follows[child] = child
                elif same is False:
                    self.notes.append(
                        f"input '{spec.name}': its '{child}' differs from top-level '{child}'; not followed"
                    )
                else:
                    self.notes.append(
                        f"input '{spec.name}': cannot compare its '{child}' with top-level '{child}'; not followed"
                    )
        for spec in self.inputs.values():
            for child, root in spec.follows.items():
                if root not in self.inputs:
                    raise DevenvSyncError(
                        f"input '{spec.name}': follows '{root}' for '{child}', which is not a top-level input", code=1
                    )


# --- Rendering -------------------------------------------------------------------------------


def render_yaml(inputs: dict[str, InputSpec], imports: list[str], tool: str) -> str:
    """The exact text of ``.vendomat/devenv.yaml``. Equal inputs give equal bytes."""

    quote = json.dumps  # a JSON string is a valid YAML double-quoted scalar
    out = [HEADER.format(tool=tool)]
    if imports:
        out.append("imports:")
        out.extend(f"  - {quote(imp)}" for imp in sorted(imports))
    out.append("inputs:")
    for name in sorted(inputs):
        spec = inputs[name]
        out.append(f"  {name}:")
        out.append(f"    url: {quote(spec.url)}")
        if not spec.flake:
            out.append("    flake: false")
        if spec.follows:
            out.append("    inputs:")
            for child in sorted(spec.follows):
                out.append(f"      {child}:")
                out.append(f"        follows: {quote(spec.follows[child])}")
    return "\n".join(out) + "\n"


def requested_inputs(inputs: dict[str, InputSpec]) -> dict[str, str]:
    return {name: spec.url for name, spec in inputs.items()}


# --- Atomic replacement ----------------------------------------------------------------------


def _replace(path: Path, data: bytes) -> None:
    """Replace ``path`` atomically, with a modification time later than the old file's (``PRE-011``)."""

    previous = path.stat().st_mtime_ns if path.exists() else 0
    scratch = path.with_name(f".{path.name}.vendomat-tmp")
    scratch.write_bytes(data)
    stamp = max(time.time_ns(), previous + 1_000_000_000)
    os.utime(scratch, ns=(stamp, stamp))
    os.replace(scratch, path)


def _restore(old: dict[Path, bytes | None]) -> None:
    """Put back the files a failed sync replaced. A file that did not exist is removed."""

    for path, data in old.items():
        if data is None:
            path.unlink(missing_ok=True)
        else:
            _replace(path, data)
    parent = next(iter(old)).parent
    try:
        parent.rmdir()  # only when it is empty: the fragment did not exist before
    except OSError:
        pass


def clear_eval_state(root: Path) -> list[str]:
    """Remove devenv's evaluation cache so a changed input set cannot read a stale result.

    Returns the names removed. The cache is derived state: devenv rebuilds it.
    """

    removed: list[str] = []
    state = root / ".devenv"
    if not state.is_dir():
        return removed
    for entry in sorted(state.glob("nix-eval-cache*")):
        try:
            entry.unlink()
            removed.append(entry.name)
        except OSError:
            continue
    return removed


# --- Workspace overrides ---------------------------------------------------------------------


def override_warnings(root: Path, generated: set[str]) -> list[str]:
    """Warn for each generated input that the workspace redeclares (``PRE-007``).

    devenv replaces a generated entry as a whole, including its ``follows``.
    """

    warnings: list[str] = []
    for name in ("devenv.yaml", "devenv.local.yaml"):
        path = root / name
        if not path.is_file():
            continue
        try:
            doc = yamlsubset.parse(path.read_text(), name)
        except (OSError, yamlsubset.YamlError) as exc:
            warnings.append(f"{name}: cannot check for overrides: {exc}")
            continue
        declared = doc.get("inputs")
        if isinstance(declared, dict):
            for input_name in sorted(set(declared) & generated):
                warnings.append(
                    f"{name} declares input '{input_name}'. It replaces the generated entry as a whole, "
                    "including its follows"
                )
    return warnings


# --- Lock ------------------------------------------------------------------------------------


def _read_lock(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def ensure_lock(root: Path, requested: dict[str, str], devenv_cmd: str) -> bool:
    """Make ``devenv.lock`` hold every requested input. Return ``True`` when it ran ``devenv update``.

    The exit status of ``devenv update`` is not a result (``NAT-026``). The function compares the
    lock before and after. When the lock still misses an input, it restores the prior lock bytes
    and raises, so the usable lock stays in place.
    """

    lock_path = root / "devenv.lock"
    prior = lock_path.read_bytes() if lock_path.exists() else None
    problems = lock_problems(_read_lock(lock_path), requested)
    if not problems:
        return False
    names = sorted({name for name, _ in problems})
    argv = [devenv_cmd, "update"] if prior is None else [devenv_cmd, "update", *names]
    try:
        done = subprocess.run(
            argv, cwd=root, capture_output=True, text=True, timeout=UPDATE_TIMEOUT, stdin=subprocess.DEVNULL
        )
        status, output = done.returncode, (done.stdout + done.stderr).strip()
    except subprocess.TimeoutExpired as exc:
        status, output = -1, f"timed out after {exc.timeout:.0f} s"
    except OSError as exc:
        raise DevenvSyncError(f"cannot run {devenv_cmd}: {exc.strerror or exc}") from exc
    after = lock_problems(_read_lock(lock_path), requested)
    if not after and status == 0:
        return True
    if not after:
        # The lock is complete although the command failed. Keep it, and say so.
        return True
    if prior is not None:
        _replace(lock_path, prior)
    elif lock_path.exists():
        lock_path.unlink()
    tail = "\n".join(output.splitlines()[-6:])
    lines = [f"{name}: {why}" for name, why in after]
    kept = "the prior devenv.lock is back in place" if prior is not None else "no devenv.lock was kept"
    raise DevenvSyncError(
        f"`{' '.join(argv[1:])}` (exit {status}) did not lock every requested input; {kept}:\n  "
        + "\n  ".join(lines)
        + (f"\n{tail}" if tail else "")
    )


# --- Entry point -----------------------------------------------------------------------------


def sync_devenv(
    root: Path,
    registry: Registry,
    tool: str,
    resolver: Resolver | None = None,
    *,
    dry_run: bool = False,
    devenv_cmd: str | None = None,
    update_lock: bool = True,
) -> DevenvResult:
    """Write the fragment for ``registry`` into ``root/.vendomat``.

    Every check runs before the first write. An unchanged workspace makes no Nix call
    (the digest names the registry, the fragment, and the module by hash).
    """

    fragment = root / FRAGMENT_DIR
    registry_bytes = (root / REGISTRY_FILE).read_bytes()
    registry_hash = sha256_hex(registry_bytes)
    digest = read_digest(fragment / DIGEST_FILE)
    command = devenv_cmd or os.environ.get("VENDOMAT_DEVENV", "devenv")

    yaml_path, nix_path = fragment / YAML_FILE, fragment / NIX_FILE
    if _unchanged(digest, registry_hash, yaml_path, nix_path, tool):
        existing = yamlsubset.parse(yaml_path.read_text(), str(yaml_path))
        requested = {
            name: body["url"] for name, body in (existing.get("inputs") or {}).items() if isinstance(body, dict)
        }
        lock_updated = False
        if update_lock and not dry_run:
            lock_updated = ensure_lock(root, requested, command)
        return DevenvResult(
            fragment,
            changed=False,
            inputs=len(requested),
            imports=len(existing.get("imports") or []),
            lock_updated=lock_updated,
            skipped=True,
        )

    found = _Discovery(registry, resolver or NixResolver())
    found.run()
    found.follows()

    text = render_yaml(found.inputs, found.imports, tool)
    module = NIX_MODULE.format(tool=tool)
    yaml_bytes, nix_bytes = text.encode(), module.encode()
    imports_sorted = sorted(found.resolved)
    body = [
        f"version {tool}",
        f"registry {registry_hash}",
        f"fragment {sha256_hex(yaml_bytes)}",
        f"module {sha256_hex(nix_bytes)}",
    ]
    body.extend(f"import {imp} {found.resolved[imp]}" for imp in imports_sorted)
    overall = sha256_hex("\n".join(body).encode())
    digest_bytes = ("\n".join([f"digest {overall}", *body]) + "\n").encode()

    warnings = override_warnings(root, set(found.inputs))
    digest_path = fragment / DIGEST_FILE
    old = {p: (p.read_bytes() if p.is_file() else None) for p in (nix_path, yaml_path, digest_path)}
    changed = old[nix_path] != nix_bytes or old[yaml_path] != yaml_bytes or old[digest_path] != digest_bytes
    lock_updated = False
    if not dry_run and changed:
        fragment.mkdir(exist_ok=True)
        # The digest goes last: an interrupted write leaves a stale digest, and the assertions fire.
        _replace(nix_path, nix_bytes)
        _replace(yaml_path, yaml_bytes)
        if old[yaml_path] != yaml_bytes:
            clear_eval_state(root)
        _replace(digest_path, digest_bytes)
    if not dry_run and update_lock:
        try:
            lock_updated = ensure_lock(root, requested_inputs(found.inputs), command)
        except DevenvSyncError:
            # Put the prior fragment back with the prior lock. The old digest then names the old
            # registry hash, so the shell reports the change as STALE and the next sync retries.
            if changed:
                _restore(old)
            raise
    return DevenvResult(
        fragment,
        changed=changed,
        inputs=len(found.inputs),
        imports=len(found.imports),
        notes=tuple(found.notes),
        warnings=tuple(warnings),
        lock_updated=lock_updated,
    )


def _unchanged(digest: dict[str, str], registry_hash: str, yaml_path: Path, nix_path: Path, tool: str) -> bool:
    if not digest or not yaml_path.is_file() or not nix_path.is_file():
        return False
    try:
        fragment_hash = sha256_hex(yaml_path.read_bytes())
        module_hash = sha256_hex(nix_path.read_bytes())
    except OSError:
        return False
    return (
        digest.get("registry") == registry_hash
        and digest.get("fragment") == fragment_hash
        and digest.get("module") == module_hash
        and digest.get("version") == tool
    )
