"""Write the generated project ``flake.nix`` from the registry (``GEN-*``).

The generated flake declares the direct inputs and hands the resolved inputs to a
project-owned file. It adds no shell, no ``devenv`` input, and no module import, and it
names no Vendomat input. Nix owns ``flake.lock``; this module never reads or writes it, and
it never reads or writes the project-owned outputs file. It only checks that file exists.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from .registry import Registry, RegistryError, Source, read_registry

REGISTRY_FILE = "vendomat.toml"
FLAKE_FILE = "flake.nix"
OUTPUTS_FILE = "flake-outputs.nix"
HEADER_PREFIX = "# GENERATED by vendomat "

#: Words Nix will not accept as a bare attribute name. A name that starts with a digit is also quoted.
_NIX_KEYWORDS = frozenset({"if", "then", "else", "assert", "with", "let", "in", "rec", "inherit", "or"})


class GenerateError(Exception):
    """A refusal or a missing file. The message names the file. ``code`` is the CLI exit status."""

    def __init__(self, message: str, code: int = 2) -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class SyncResult:
    """``changed`` says the file differs from the new text. A dry run reports it and writes nothing."""

    path: Path
    changed: bool
    inputs: int
    registry: Registry


def tool_version() -> str:
    try:
        return version("vendomat")
    except PackageNotFoundError:
        return "0+unknown"


def render(registry: Registry, tool: str) -> str:
    """The exact text of the generated flake. Equal registry and tool version give equal bytes."""

    lines = [
        f"{HEADER_PREFIX}{tool}. Do not edit.",
        f"# registry-digest: {registry.digest}",
        "{",
        "  inputs = {",
    ]
    for source in registry.sources:
        lines.extend(_stanza(source))
    lines += [
        "  };",
        "",
        f"  outputs = inputs: import ./{OUTPUTS_FILE} inputs;",
        "}",
        "",
    ]
    return "\n".join(lines)


def _attr(name: str) -> str:
    if name[0].isdigit() or name in _NIX_KEYWORDS:
        return f'"{name}"'
    return name


def _stanza(source: Source) -> list[str]:
    name = _attr(source.name)
    lines = [f'    {name}.url = "{source.url}";']
    if not source.flake:
        lines.append(f"    {name}.flake = false;")
    lines.extend(f'    {name}.inputs.{root}.follows = "{root}";' for root in source.follows)
    return lines


def sync_flake(root: Path, tool: str | None = None, *, dry_run: bool = False) -> SyncResult:
    """Generate ``flake.nix`` in ``root``.

    Every check runs before the first write, so a refusal leaves the tree untouched. With
    ``dry_run`` the checks run and nothing is written.
    """

    registry_path = root / REGISTRY_FILE
    if not registry_path.is_file():
        raise GenerateError(f"{registry_path}: no registry here; create {REGISTRY_FILE} first")

    try:
        registry = read_registry(registry_path)
    except RegistryError as exc:
        raise GenerateError(str(exc)) from exc

    # A stat call only. The project-owned file is never opened.
    outputs = root / OUTPUTS_FILE
    if not outputs.is_file():
        raise GenerateError(
            f"{outputs}: the project-owned outputs file is missing; write it, then track it in Git before Nix reads it"
        )

    flake = root / FLAKE_FILE
    if flake.exists() and not _has_header(flake):
        raise GenerateError(
            f"{flake}: this flake.nix has no generated header, so it is hand-authored; "
            "Vendomat will not overwrite it. Move its outputs into "
            f"{OUTPUTS_FILE} and delete it, or keep it and do not run sync",
            code=1,
        )

    text = render(registry, tool or tool_version())
    new = text.encode()
    if flake.exists() and flake.read_bytes() == new:
        return SyncResult(flake, changed=False, inputs=len(registry.sources), registry=registry)
    if not dry_run:
        scratch = flake.with_name(f".{FLAKE_FILE}.vendomat-tmp")
        scratch.write_bytes(new)
        os.replace(scratch, flake)
    return SyncResult(flake, changed=True, inputs=len(registry.sources), registry=registry)


def _has_header(flake: Path) -> bool:
    with flake.open("rb") as handle:
        first = handle.readline(200)
    return first.decode(errors="replace").startswith(HEADER_PREFIX)
