"""Install per-dependency knowledge skills into a consumer repo + record a manifest.

Mirrors :mod:`repoman.devman.install` (copied, not imported — vendomat carries no `repoman`
dependency). The differences from devman are deliberate:

- skills are **usage-gated**: only libs the repo actually depends on are installed (the
  intersection of ``expected_libs`` with the repo's resolved dep set);
- each skill lands as a **flat sibling** ``<skills_dir>/dep-<lib>/SKILL.md`` (the ``dep-`` prefix
  keeps vendomat's skills from clobbering repoman/devman's ``<name>/SKILL.md`` — different names,
  they coexist);
- the manifest is ``.vendor-source`` and records, per installed skill, the **pin** the skill was
  written against (from each lib's ``meta.toml``) so M4 can flag staleness.

Pure functions over explicit ``Path`` args — fully unit-testable; the CLI and devenv module supply
the real ``vendor_root`` / ``skills_dir`` / ``repo_root``.
"""

from __future__ import annotations

import shutil
import tomllib
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from .deps import normalize

MANIFEST = ".vendor-source"
LIB_PREFIX = "dep-"


def _libs_dir(vendor_root: Path) -> Path:
    return vendor_root / "libs"


def expected_libs(vendor_root: Path) -> list[str]:
    """Lib names under ``vendor/libs/<lib>/`` that ship a ``SKILL.md`` (sorted)."""

    libs = _libs_dir(vendor_root)
    if not libs.is_dir():
        return []
    return sorted(p.name for p in libs.iterdir() if (p / "SKILL.md").is_file())


def lib_pin(vendor_root: Path, lib: str) -> str:
    """The version a lib's skill was written against (``[lib].pin`` in its ``meta.toml``).

    Returns ``"unpinned"`` if the meta file or key is absent — the skill still installs; staleness
    just cannot be judged for it.
    """

    meta = _libs_dir(vendor_root) / lib / "meta.toml"
    if not meta.is_file():
        return "unpinned"
    data = tomllib.loads(meta.read_text())
    pin = data.get("lib", {}).get("pin")
    return str(pin) if pin else "unpinned"


def _vendomat_version() -> str:
    try:
        return version("vendomat")
    except PackageNotFoundError:  # pragma: no cover - only when run uninstalled
        return "0+unknown"


def matched_libs(vendor_root: Path, deps: set[str]) -> list[str]:
    """Libs with a skill whose normalized name is in the repo's (normalized) dep set."""

    normalized_deps = {normalize(d) for d in deps}
    return [lib for lib in expected_libs(vendor_root) if normalize(lib) in normalized_deps]


def install_knowledge(vendor_root: Path, deps: set[str], skills_dir: str, repo_root: Path) -> list[Path]:
    """Install knowledge skills for the deps the repo actually uses; write ``.vendor-source``.

    Copies each matched ``vendor/libs/<lib>/SKILL.md`` to ``<repo>/<skills_dir>/dep-<lib>/SKILL.md``
    and writes the drift manifest. Idempotent: re-running with the same inputs overwrites in place
    and produces a byte-stable manifest (no duplicate entries).
    """

    libs = matched_libs(vendor_root, deps)
    skills_root = repo_root / skills_dir
    written: list[Path] = []

    for lib in libs:
        dest = skills_root / f"{LIB_PREFIX}{lib}"
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copy2(_libs_dir(vendor_root) / lib / "SKILL.md", dest / "SKILL.md")
        written.append(dest / "SKILL.md")

    manifest = skills_root / MANIFEST
    manifest.parent.mkdir(parents=True, exist_ok=True)
    pins = "\n".join(f"  {LIB_PREFIX}{lib} @ {lib_pin(vendor_root, lib)}" for lib in libs)
    manifest.write_text(
        "Generated by vendomat (knowledge layer). Do not edit; re-run `vendomat sync`.\n"
        f"vendomat version: {_vendomat_version()}\n"
        f"skills: {', '.join(f'{LIB_PREFIX}{lib}' for lib in libs)}\n"
        "pins:\n" + (pins + "\n" if pins else "")
    )
    written.append(manifest)
    return written
