"""Git inspection, synchronization, source maps, and diagnostics for the source catalog."""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path

from .catalog import CatalogEntry, CatalogError, read_catalog
from .checks import SelfCheck
from .deps import normalize, read_deps, read_resolved_versions

SOURCE_MAP = Path(".vendomat/sources.toml")
SOURCE_MAP_HEADER = (
    "# Generated by `vendomat vendor sync`; do not edit.\n"
    "# Source checkouts are for investigation only, never Python installation.\n\n"
    "[sources]\n"
)


class SourceError(RuntimeError):
    """A source checkout cannot be inspected or changed safely."""


@dataclass(frozen=True)
class SyncResult:
    """User-visible actions performed or planned by source synchronization."""

    actions: tuple[str, ...]
    relevant: tuple[str, ...]
    map_changed: bool


@dataclass(frozen=True)
class SourceState:
    """Read-only state for one relevant catalog source."""

    entry: CatalogEntry
    path: Path
    exists: bool
    is_git: bool = False
    current: str | None = None
    dirty: bool = False
    detached: bool | None = None
    remote: str | None = None
    error: str = ""


@dataclass(frozen=True)
class GitResult:
    """Captured output from one explicit Git subprocess call."""

    returncode: int
    stdout: str
    stderr: str


class Git:
    """Small injectable subprocess boundary for narrowly scoped Git operations."""

    def run(self, cwd: Path, *args: str) -> GitResult:
        try:
            result = subprocess.run(
                ["git", *args],
                cwd=cwd,
                check=False,
                capture_output=True,
                text=True,
            )
        except OSError as exc:
            raise SourceError(f"could not run git in {cwd}: {exc}") from exc
        return GitResult(result.returncode, result.stdout, result.stderr)

    def require(self, cwd: Path, *args: str) -> str:
        result = self.run(cwd, *args)
        if result.returncode:
            detail = result.stderr.strip() or result.stdout.strip()
            raise SourceError(f"git {' '.join(args)} failed in {cwd}: {detail}")
        return result.stdout.strip()

    def is_checkout(self, path: Path) -> bool:
        result = self.run(path, "rev-parse", "--is-inside-work-tree")
        return result.returncode == 0 and result.stdout.strip() == "true"

    def head(self, path: Path) -> str:
        return self.require(path, "rev-parse", "HEAD")

    def dirty(self, path: Path) -> bool:
        return bool(self.require(path, "status", "--porcelain", "--untracked-files=normal"))

    def detached(self, path: Path) -> bool:
        result = self.run(path, "symbolic-ref", "-q", "HEAD")
        if result.returncode == 0:
            return False
        if result.returncode == 1:
            return True
        detail = result.stderr.strip() or result.stdout.strip()
        raise SourceError(f"git symbolic-ref failed in {path}: {detail}")

    def remote(self, path: Path) -> str:
        return self.require(path, "remote", "get-url", "origin")

    def clone(self, repository: str, path: Path) -> None:
        try:
            result = subprocess.run(
                ["git", "clone", "--no-checkout", repository, str(path)],
                cwd=path.parent,
                check=False,
                capture_output=True,
                text=True,
            )
        except OSError as exc:
            raise SourceError(f"could not run git clone for {repository}: {exc}") from exc
        if result.returncode:
            detail = result.stderr.strip() or result.stdout.strip()
            raise SourceError(f"git clone failed for {repository}: {detail}")

    def fetch_and_checkout(self, path: Path, rev: str) -> None:
        self.require(path, "fetch", "--no-tags", "origin", rev)
        self.require(path, "checkout", "--detach", rev)

    def checkout_detached(self, path: Path, rev: str) -> None:
        self.require(path, "checkout", "--detach", rev)


def relevant_entries(catalog: dict[str, CatalogEntry], dependencies: set[str]) -> list[CatalogEntry]:
    """Catalog entries used by the consumer, in deterministic distribution-name order."""

    normalized = {normalize(dependency) for dependency in dependencies}
    return [catalog[name] for name in sorted(catalog.keys() & normalized)]


def source_path(entry: CatalogEntry, source_root: Path, consumer_root: Path) -> Path:
    """Resolve the canonical local checkout path for one entry."""

    relative = entry.local.path if entry.package.kind == "project" else entry.local.cache
    assert relative is not None  # Pydantic's cross-field validator guarantees the active field.
    if entry.package.kind == "project":
        return (consumer_root / relative).resolve()
    root = source_root.resolve()
    path = (root / relative).resolve()
    if not path.is_relative_to(root):
        raise SourceError(f"{entry.package.name}: managed cache resolves outside source root: {path}")
    return path


def source_map_text(entries: list[CatalogEntry], source_root: Path, consumer_root: Path) -> str:
    """Render byte-stable paths and reviewed revisions for relevant catalog sources."""

    lines = [SOURCE_MAP_HEADER]
    ordered = sorted(entries, key=lambda item: item.package.name)
    for entry in ordered:
        if entry.package.kind == "project":
            value = entry.local.path
            assert value is not None
            rendered = value.as_posix()
        else:
            rendered = str(source_path(entry, source_root, consumer_root))
        lines.append(f"{entry.package.name} = {json.dumps(rendered, ensure_ascii=False)}\n")
    lines.append("\n[revisions]\n")
    for entry in ordered:
        lines.append(f'{entry.package.name} = "{entry.package.rev}"\n')
    return "".join(lines)


def _write_atomic_if_changed(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text() == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
            temporary = Path(handle.name)
        os.replace(temporary, path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()
    return True


def _inspect(entry: CatalogEntry, source_root: Path, consumer_root: Path, git: Git) -> SourceState:
    path = source_path(entry, source_root, consumer_root)
    if not path.exists():
        return SourceState(entry=entry, path=path, exists=False)
    if not path.is_dir():
        return SourceState(entry=entry, path=path, exists=True, error="not a Git checkout")
    try:
        if not git.is_checkout(path):
            return SourceState(entry=entry, path=path, exists=True, error="not a Git checkout")
        return SourceState(
            entry=entry,
            path=path,
            exists=True,
            is_git=True,
            current=git.head(path),
            dirty=git.dirty(path),
            detached=git.detached(path),
            remote=git.remote(path) if entry.package.kind == "vendor" else None,
        )
    except SourceError as exc:
        return SourceState(entry=entry, path=path, exists=True, is_git=True, error=str(exc))


def _sync_project(entry: CatalogEntry, state: SourceState) -> list[str]:
    name = entry.package.name
    if not state.exists:
        raise SourceError(f"{name}: owned project checkout is missing: {state.path}")
    if not state.is_git or state.error:
        raise SourceError(f"{name}: {state.error or 'not a Git checkout'}: {state.path}")
    if state.current != entry.package.rev:
        raise SourceError(
            f"{name}: owned project is at {state.current}, expected {entry.package.rev}; "
            "Vendomat will not modify a personal checkout"
        )
    detail = f"{name}: project checkout verified at {state.current}"
    if state.dirty:
        detail += " (dirty working tree left untouched)"
    return [detail]


def _sync_vendor(entry: CatalogEntry, state: SourceState, git: Git, dry_run: bool) -> list[str]:
    name = entry.package.name
    path = state.path
    if not state.exists:
        if dry_run:
            return [f"{name}: would clone {entry.package.repository} and check out {entry.package.rev}"]
        path.parent.mkdir(parents=True, exist_ok=True)
        git.clone(entry.package.repository, path)
        git.fetch_and_checkout(path, entry.package.rev)
        return [f"{name}: cloned and checked out detached {entry.package.rev}"]

    if not state.is_git or state.error:
        raise SourceError(f"{name}: {state.error or 'not a Git checkout'}: {path}")
    if state.remote != entry.package.repository:
        raise SourceError(
            f"{name}: origin is {state.remote!r}, expected catalog repository {entry.package.repository!r}"
        )
    if state.dirty:
        raise SourceError(f"{name}: managed clone is dirty; preserve or discard the investigation edits first: {path}")

    if state.current == entry.package.rev and state.detached:
        return [f"{name}: managed clone already at detached {entry.package.rev}"]
    if dry_run:
        return [f"{name}: would fetch and check out detached {entry.package.rev}"]
    if state.current == entry.package.rev:
        git.checkout_detached(path, entry.package.rev)
    else:
        git.fetch_and_checkout(path, entry.package.rev)
    return [f"{name}: checked out detached {entry.package.rev}"]


def sync_sources(
    catalog_root: Path,
    source_root: Path,
    consumer_root: Path,
    *,
    dry_run: bool = False,
    git: Git | None = None,
) -> SyncResult:
    """Synchronize relevant sources and atomically write the consumer's generated map."""

    boundary = git or Git()
    catalog = read_catalog(catalog_root)
    try:
        dependencies = read_deps(consumer_root)
    except (OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as exc:
        raise SourceError(f"could not read dependencies from {consumer_root}: {exc}") from exc
    relevant = relevant_entries(catalog, dependencies)
    actions: list[str] = []
    for entry in relevant:
        state = _inspect(entry, source_root, consumer_root, boundary)
        if entry.package.kind == "project":
            actions.extend(_sync_project(entry, state))
        else:
            actions.extend(_sync_vendor(entry, state, boundary, dry_run))

    map_path = consumer_root / SOURCE_MAP
    expected = source_map_text(relevant, source_root, consumer_root)
    if dry_run:
        changed = not map_path.is_file() or map_path.read_text() != expected
        actions.append(f"source map: would {'write' if changed else 'leave unchanged'} {map_path}")
    else:
        changed = _write_atomic_if_changed(map_path, expected)
        actions.append(f"source map: {'wrote' if changed else 'unchanged'} {map_path}")
    return SyncResult(
        actions=tuple(actions),
        relevant=tuple(entry.package.name for entry in relevant),
        map_changed=changed,
    )


def _state_detail(state: SourceState, installed: str | None) -> str:
    entry = state.entry
    if not state.exists:
        current = "missing"
    elif not state.is_git:
        current = "not-git"
    else:
        current = state.current or "unknown"
    fields = [
        f"kind={entry.package.kind}",
        f"expected={entry.package.rev}",
        f"path={state.path}",
        f"current={current}",
        f"dirty={'yes' if state.dirty else 'no'}",
        f"installed={installed or 'unknown'}",
    ]
    if entry.package.kind == "vendor" and state.detached is not None:
        fields.append(f"detached={'yes' if state.detached else 'no'}")
    return " ".join(fields)


def source_status(
    catalog_root: Path,
    source_root: Path,
    consumer_root: Path,
    git: Git | None = None,
) -> list[str]:
    """Return concise read-only status lines for every relevant catalog entry."""

    boundary = git or Git()
    catalog = read_catalog(catalog_root)
    try:
        dependencies = read_deps(consumer_root)
        installed = read_resolved_versions(consumer_root)
    except (OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as exc:
        raise SourceError(f"could not read dependencies from {consumer_root}: {exc}") from exc
    lines: list[str] = []
    for entry in relevant_entries(catalog, dependencies):
        state = _inspect(entry, source_root, consumer_root, boundary)
        lines.append(f"{entry.package.name}: {_state_detail(state, installed.get(entry.package.name))}")
    return lines


def _entry_checks(state: SourceState, installed: str | None) -> list[SelfCheck]:
    name = state.entry.package.name
    expected = state.entry.package.rev
    detail = _state_detail(state, installed)
    level = "ok"
    reason = "source ready"
    if not state.exists:
        level, reason = "fail", "missing checkout"
    elif not state.is_git:
        level, reason = "fail", state.error or "not a Git checkout"
    elif state.error:
        level, reason = "fail", state.error
    elif state.current != expected:
        level, reason = "fail", "wrong revision"
    elif state.entry.package.kind == "vendor" and state.remote != state.entry.package.repository:
        level, reason = "fail", "wrong origin repository"
    elif state.entry.package.kind == "vendor" and state.dirty:
        level, reason = "fail", "dirty managed clone"
    elif state.entry.package.kind == "vendor" and not state.detached:
        level, reason = "fail", "managed clone HEAD is attached"

    checks = [SelfCheck(name=f"source:{name}", level=level, detail=f"{reason}; {detail}")]
    if state.entry.package.kind == "project" and state.dirty:
        checks.append(
            SelfCheck(
                name=f"source:{name}:working-tree",
                level="warn",
                detail="dirty owned-project checkout; Vendomat will not modify it",
            )
        )
    return checks


def source_checks(
    catalog_root: Path,
    source_root: Path,
    consumer_root: Path,
    git: Git | None = None,
) -> list[SelfCheck]:
    """Diagnose catalog, checkout, source-map, and coverage state under the shared contract."""

    boundary = git or Git()
    try:
        catalog = read_catalog(catalog_root)
        dependencies = read_deps(consumer_root)
        installed = read_resolved_versions(consumer_root)
    except (CatalogError, OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as exc:
        return [SelfCheck(name="source:catalog", level="fail", detail=str(exc))]

    relevant = relevant_entries(catalog, dependencies)
    checks = [SelfCheck(name="source:catalog", level="ok", detail=f"{len(catalog)} valid entry(s)")]
    for entry in relevant:
        try:
            state = _inspect(entry, source_root, consumer_root, boundary)
        except SourceError as exc:
            checks.append(SelfCheck(name=f"source:{entry.package.name}", level="fail", detail=str(exc)))
        else:
            checks.extend(_entry_checks(state, installed.get(entry.package.name)))

    unknown = sorted(dependencies - catalog.keys())
    coverage_detail = (
        f"dependencies without catalog entries: {', '.join(unknown)}" if unknown else "all dependencies cataloged"
    )
    checks.append(
        SelfCheck(
            name="source:coverage",
            level="warn" if unknown else "ok",
            detail=coverage_detail,
        )
    )

    if relevant:
        map_path = consumer_root / SOURCE_MAP
        expected = source_map_text(relevant, source_root, consumer_root)
        if not map_path.is_file():
            checks.append(
                SelfCheck(name="source:map", level="fail", detail=f"missing {map_path}; run `vendomat vendor sync`")
            )
        else:
            try:
                stale = map_path.read_text() != expected
            except OSError as exc:
                checks.append(SelfCheck(name="source:map", level="fail", detail=f"cannot read {map_path}: {exc}"))
            else:
                checks.append(
                    SelfCheck(
                        name="source:map",
                        level="fail" if stale else "ok",
                        detail="stale generated map; run `vendomat vendor sync`"
                        if stale
                        else "generated map is current",
                    )
                )
    return checks
