#!/usr/bin/env python3
"""Prototype Vendomat pre-resolver. Run: python -I vendomat_sync.py <workspace-dir>

Reads  <workspace>/vendomat.json   (the "registry")
Writes <workspace>/.vendomat/devenv.yaml, devenv.nix, digest

Registry format:
  {"inputs":  {"<name>": {"url": "...", "flake": false?}},   direct inputs
   "imports": ["<input>/<dir>", ...],                        imports of input sources
   "flatten": false,                                         also lift nested inputs to top level
   "leaf":    ["nixpkgs"]}                                   inputs flatten never descends into

Algorithm
  1. For each import "<input>/<dir>": fetch the input source (nix flake prefetch),
     read <storePath>/<dir>/devenv.yaml, collect its `inputs:` and `imports:`
     recursively. Every collected input becomes a TOP-LEVEL input.
  2. For every top-level flake input X, ask nix for X's own direct inputs
     (nix flake metadata). If X has an input N that is also top-level, emit
     X.inputs.N.follows = N (one level only; devenv drops deeper follows).
     With "flatten", lift N to top level first when it is missing.
  3. Write the fragment and a digest.
"""
import hashlib
import json
import subprocess
import sys
from pathlib import Path


# ---------------------------------------------------------------- mini YAML
def _scalar(text):
    text = text.strip()
    if text in ("{}",):
        return {}
    if text in ("[]",):
        return []
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
        return text[1:-1]
    if text in ("true", "false"):
        return text == "true"
    return text


def parse_yaml(text):
    """Parse block maps, lists of scalars, comments. No anchors, no flow style except {} and []."""
    lines = []
    for raw in text.splitlines():
        stripped = raw.split(" #", 1)[0] if " #" in raw else raw
        if stripped.strip().startswith("#") or not stripped.strip():
            continue
        lines.append((len(stripped) - len(stripped.lstrip(" ")), stripped.strip()))
    pos = 0

    def block(indent):
        nonlocal pos
        if pos < len(lines) and lines[pos][1].startswith("- "):
            out = []
            while pos < len(lines) and lines[pos][0] == indent and lines[pos][1].startswith("- "):
                out.append(_scalar(lines[pos][1][2:]))
                pos += 1
            return out
        out = {}
        while pos < len(lines) and lines[pos][0] == indent:
            body = lines[pos][1]
            key, _, rest = body.partition(":")
            pos += 1
            if rest.strip():
                out[key.strip()] = _scalar(rest)
            elif pos < len(lines) and lines[pos][0] > indent:
                out[key.strip()] = block(lines[pos][0])
            elif pos < len(lines) and lines[pos][0] == indent and lines[pos][1].startswith("- "):
                out[key.strip()] = block(indent)
            else:
                out[key.strip()] = {}
        return out

    return block(lines[0][0]) if lines else {}


def emit_yaml(inputs, imports):
    q = json.dumps  # a JSON string is a valid YAML double-quoted scalar
    out = ["# Generated by vendomat sync. Do not edit."]
    if imports:
        out.append("imports:")
        out += [f"  - {q(i)}" for i in imports]
    out.append("inputs:")
    for name in sorted(inputs):
        spec = inputs[name]
        out.append(f"  {name}:")
        out.append(f"    url: {q(spec['url'])}")
        if spec.get("flake") is False:
            out.append("    flake: false")
        if spec.get("inputs"):
            out.append("    inputs:")
            for sub in sorted(spec["inputs"]):
                out.append(f"      {sub}:")
                out.append(f"        follows: {q(spec['inputs'][sub]['follows'])}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- nix access
_cache = {}


def nix_json(*args):
    key = args
    if key not in _cache:
        r = subprocess.run(["nix", *args], capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"vendomat sync: nix {' '.join(args)} failed:\n{r.stderr}")
        _cache[key] = json.loads(r.stdout)
    return _cache[key]


def prefetch(url):
    return nix_json("flake", "prefetch", "--json", url)


def metadata(url):
    return nix_json("flake", "metadata", "--json", "--no-write-lock-file", url)


def direct_inputs_of(url):
    """Return {input name: original-ref dict} for the flake at url."""
    locks = metadata(url)["locks"]
    nodes = locks["nodes"]
    out = {}
    for name, target in nodes[locks["root"]].get("inputs", {}).items():
        if isinstance(target, list):  # follows inside the flake's own lock: no own node
            continue
        out[name] = nodes[target]["original"]
    return out


def original_to_url(o):
    if o["type"] == "git":
        return o["url"] + (f"?ref={o['ref']}" if o.get("ref") else "")
    if o["type"] == "github":
        return f"github:{o['owner']}/{o['repo']}" + (f"/{o['ref']}" if o.get("ref") else "")
    return None


def same_source(url, o):
    """True/False when comparable, None when unknown."""
    if o["type"] == "git" and url.startswith("git"):
        base, _, q = url.partition("?")
        ref = dict(p.split("=", 1) for p in q.split("&") if "=" in p).get("ref")
        return base == o["url"] and ref == o.get("ref")
    if o["type"] == "github" and url.startswith("github:"):
        return url == original_to_url(o)
    return None


# ---------------------------------------------------------------- main
def sha(data):
    return hashlib.sha256(data if isinstance(data, bytes) else data.encode()).hexdigest()


def main(ws):
    ws = Path(ws).resolve()
    reg_bytes = (ws / "vendomat.json").read_bytes()
    reg = json.loads(reg_bytes)
    top = {k: dict(v) for k, v in reg["inputs"].items()}
    direct = set(top)
    imports = []
    notes = []
    resolved = {}

    def add(name, spec, origin):
        if name in top:
            if top[name]["url"] == spec["url"]:
                return
            if name in direct:
                notes.append(f"{name}: registry url wins over {origin}")
                return
            sys.exit(f"vendomat sync: conflict on input '{name}': {top[name]['url']} vs {spec['url']} ({origin})")
        top[name] = {"url": spec["url"], **({"flake": False} if spec.get("flake") is False else {})}

    def walk(imp):
        if imp in imports:
            return
        imports.append(imp)
        inp, _, sub = imp.partition("/")
        if inp not in top:
            sys.exit(f"vendomat sync: import '{imp}' names unknown input '{inp}'")
        pf = prefetch(top[inp]["url"])
        resolved[imp] = {"narHash": pf["hash"], "rev": pf["locked"].get("rev")}
        yml = Path(pf["storePath"]) / sub / "devenv.yaml"
        if not yml.exists():
            return
        doc = parse_yaml(yml.read_text())
        for name, spec in (doc.get("inputs") or {}).items():
            add(name, spec, imp)
        for nested in doc.get("imports") or []:
            if not nested.startswith("."):
                walk(nested)

    for imp in reg.get("imports", []):
        walk(imp)

    leaf = set(reg.get("leaf", ["nixpkgs"]))
    flatten = bool(reg.get("flatten"))
    done = set()
    todo = [n for n in top if top[n].get("flake") is not False]
    while todo:
        x = todo.pop(0)
        if x in done:
            continue
        done.add(x)
        for n, orig in direct_inputs_of(top[x]["url"]).items():
            if n == x:
                continue
            if n not in top and flatten and x not in leaf:
                url = original_to_url(orig)
                if url is None:
                    notes.append(f"{x}.{n}: cannot flatten type {orig['type']}")
                    continue
                top[n] = {"url": url}
                todo.append(n)
            if n in top:
                same = same_source(top[n]["url"], orig)
                if same is False:
                    notes.append(f"{x}.{n}: not followed, source differs from top-level {n}")
                    continue
                top[x].setdefault("inputs", {})[n] = {"follows": n}

    out = ws / ".vendomat"
    out.mkdir(exist_ok=True)
    yaml_text = emit_yaml(top, imports)
    (out / "devenv.yaml").write_text(yaml_text)
    (out / "devenv.nix").write_text(NIX_TEMPLATE)
    full = sha(json.dumps({"registry": reg, "resolved": resolved, "inputs": top}, sort_keys=True))
    (out / "digest").write_text(
        f"digest {full}\nregistry {sha(reg_bytes)}\nfragment {sha(yaml_text)}\n"
    )
    for n in notes:
        print("note:", n, file=sys.stderr)
    print(f"vendomat sync: {len(top)} inputs, {len(imports)} imports, digest {full[:12]}")


NIX_TEMPLATE = r'''# Generated by vendomat sync. Do not edit.
# A failing enterShell task does NOT stop `devenv shell` (devenv/src/devenv/mod.rs:2239-2241).
# An evaluation error does. So the freshness check is an assertion, evaluated on every shell entry.
{ lib, config, ... }:
let
  root = config.devenv.root;
  digestPath = /. + "${root}/.vendomat/digest";
  registryPath = /. + "${root}/vendomat.json";
  fragmentPath = /. + "${root}/.vendomat/devenv.yaml";
  recorded =
    key:
    let
      hits = lib.filter (l: lib.hasPrefix "${key} " l) (lib.splitString "\n" (builtins.readFile digestPath));
    in
    if hits == [ ] then "missing" else lib.removePrefix "${key} " (builtins.head hits);
  haveDigest = builtins.pathExists digestPath;
in
{
  assertions = [
    {
      assertion = haveDigest;
      message = "vendomat: .vendomat/digest is missing. Run: vendomat sync";
    }
    {
      assertion = !haveDigest || builtins.hashFile "sha256" registryPath == recorded "registry";
      message = "vendomat: STALE. vendomat.json changed since the last sync. Run: vendomat sync";
    }
    {
      assertion = !haveDigest || builtins.hashFile "sha256" fragmentPath == recorded "fragment";
      message = "vendomat: STALE. .vendomat/devenv.yaml was edited by hand. Run: vendomat sync";
    }
  ];
}
'''

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: python -I vendomat_sync.py <workspace-dir>")
    main(sys.argv[1])
